### ISSUE TITLE
The plugin throws 'Error: Cannot read properties of undefined (reading 'icon')' with a new Sanity NextJS App. 

### ISSUE THREAD

**Issue by vazra** [gustavorino/sanity-plugin-draft-review-v3#1]
I tried this plugin in a new Sanity - NextJS App. 

I get error "The draft-review tool crashed" as shown in the screenshot. 

![Screenshot 2023-08-06 at 3 48 10 PM](https://github.com/gustavorino/sanity-plugin-draft-review-v3/assets/7609895/60b97c03-9452-4e98-bfbf-14492b5fe4c3)

**Comment by vazra** [comment]
@gustavorino any thoughts why this might be happening?

**Comment by gustavorino** [comment]
@vazra It looks like you are running sanity studio version 2, can you run the following command and paste the result here?

```shell
npx sanity versions
```

**Comment by vazra** [comment]
No I'm using v3. I am not at the computer now. Will send you the exact version later today

**Comment by gustavorino** [comment]
@vazra This problem happened to me when I had a draft record with an unregistered _type on the schema. Fixed on 0.0.4. Please update.

Thanks for reporting!
